name: Docker Image CI

on:
    # push:
    #     branches: ["main"]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: setup java
              uses: actions/setup-java@v4
              with:
                  java-version: "17"
                  distribution: "temurin"

            - name: Build project with Maven
              run: mvn -B package --file pom.xml

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build Docker image
              env:
                  IMAGE_TAG: "${{ secrets.DOCKER_ID }}/boardshack:${{ github.sha }}"
              run: |
                  docker build . -t $IMAGE_TAG -f Dockerfile
            
            - name: login to docker registry
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_ID }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Push Docker image to Docker hub
              env:
                  IMAGE_TAG: "${{ secrets.DOCKER_ID }}/boardshack:${{ github.sha }}"
              run: |
                  docker push $IMAGE_TAG
