name: Docker Image CI Github Container Registry

on:
    workflow_dispatch:
    # push:
    #     branches: ["main"]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: setup java
              uses: actions/setup-java@v4
              with:
                  java-version: "17"
                  distribution: "temurin"

            - name: Build project with Maven
              run: mvn -B package --file pom.xml

            - name: "Login to GitHub Container Registry"
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: "Build Inventory Image"
              run: |
                  docker build . --tag ${{ env.REGISTRY }}/misbahashimt/bgame:latest
                  docker push ${{ env.REGISTRY }}/misbahashimt/bgame:latest
